// <auto-generated />
using System;
using BlazorPersonalWebsite.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorPersonalWebsite.EntityFramework.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    [Migration("20210422204642_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorPersonalWebsite.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobApplicationRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplication");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareProject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Skill action calculator for video game Runescape",
                            Name = "Runescape Calculator",
                            ProjectRef = "rsCalc"
                        });
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProjectImage", b =>
                {
                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoftwareProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SoftwareProjectId1")
                        .HasColumnType("int");

                    b.HasKey("ImageUrl");

                    b.HasIndex("SoftwareProjectId");

                    b.HasIndex("SoftwareProjectId1");

                    b.ToTable("SoftwareProjectImage");

                    b.HasData(
                        new
                        {
                            ImageUrl = "images\\software-images\\rs-calculator\\1.png",
                            Description = "Agility skill calculator",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            ImageUrl = "images\\software-images\\rs-calculator\\2.png",
                            Description = "Fishing skill calculator",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            ImageUrl = "images\\software-images\\rs-calculator\\3.png",
                            Description = "Dropdown showing which skills are included",
                            SoftwareProjectId = 1
                        },
                        new
                        {
                            ImageUrl = "images\\software-images\\rs-calculator\\4.png",
                            Description = "Dropdown showing skill subcategories",
                            SoftwareProjectId = 1
                        });
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkImage", b =>
                {
                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WoodworkProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("WoodworkProjectId1")
                        .HasColumnType("int");

                    b.HasKey("ImageUrl");

                    b.HasIndex("WoodworkProjectId");

                    b.HasIndex("WoodworkProjectId1");

                    b.ToTable("WoodworkImage");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WoodworkProject");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProjectImage", b =>
                {
                    b.HasOne("BlazorPersonalWebsite.Models.SoftwareProject", null)
                        .WithMany()
                        .HasForeignKey("SoftwareProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPersonalWebsite.Models.SoftwareProject", null)
                        .WithMany("Images")
                        .HasForeignKey("SoftwareProjectId1");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkImage", b =>
                {
                    b.HasOne("BlazorPersonalWebsite.Models.WoodworkProject", null)
                        .WithMany()
                        .HasForeignKey("WoodworkProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorPersonalWebsite.Models.WoodworkProject", null)
                        .WithMany("Images")
                        .HasForeignKey("WoodworkProjectId1");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProject", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProject", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
