// <auto-generated />
using System;
using BlazorPersonalWebsite.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorPersonalWebsite.EntityFramework.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    [Migration("20210421180205_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorPersonalWebsite.Models.Image", b =>
                {
                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoftwareProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("WoodworkProjectId")
                        .HasColumnType("int");

                    b.HasKey("ImageUrl");

                    b.HasIndex("SoftwareProjectId");

                    b.HasIndex("WoodworkProjectId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobApplicationRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplication");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareProject");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WoodworkProject");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.Image", b =>
                {
                    b.HasOne("BlazorPersonalWebsite.Models.SoftwareProject", null)
                        .WithMany("Images")
                        .HasForeignKey("SoftwareProjectId");

                    b.HasOne("BlazorPersonalWebsite.Models.WoodworkProject", null)
                        .WithMany("Images")
                        .HasForeignKey("WoodworkProjectId");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.SoftwareProject", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BlazorPersonalWebsite.Models.WoodworkProject", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
